### ISSUE TITLE
Not an issue, just a small note

### ISSUE THREAD

**Issue by zagnuts** [popcorncx/raven-mqtt#1]
Thanks for the script! FWIW I found that for whatever reason my raven was pumping out insane Demand numbers every now and then eg  "Demand": 4294967226. I was reading the data into Home Assistant and it meant that graphs over time looked a little odd. Solved with a little hack as follows:

```
sensor:
  - platform: mqtt
    unique_id: 666-1
    name: "InstantaneousDemand"
    state_topic: "home/power/InstantaneousDemand"
    unit_of_measurement: "W"
    state_class: measurement
    device_class: energy
    value_template: >-
      {%- if value_json.Demand|float >= 1000000000 -%}
      0
      {%- else -%}
      {{ value_json.Demand}}
      {%- endif -%}
```
Basically, if the Demand number turns out to be equal to or more than a thousand MW then let's just make that a zero because I'm pretty sure even my death ray uses less power than that.... ;-)

**Comment by popcorncx** [comment]
It turns out this was an issue and I have pushed a fix.

I got solar panels installed today and started to get crazy numbers, Looking at the raw data I worked out that it was a signed/unsigned issue and that is how negative demand (ie feeding back into the grid) is represented.

Do you have solar or other generation?

**Comment by zagnuts** [comment]
> Do you have solar or other generation?

Yep, so sounds like that was the issue. Cheers!
